# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T02:21:58+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class GoogleExampleLibraryagentV1Book(BaseModel):
    author: Optional[str] = Field(None, description='The name of the book author.')
    name: Optional[str] = Field(
        None,
        description='The resource name of the book. Book names have the form `shelves/{shelf_id}/books/{book_id}`. The name is ignored when creating a book.',
    )
    read: Optional[bool] = Field(
        None, description='Value indicating whether the book has been read.'
    )
    title: Optional[str] = Field(None, description='The title of the book.')


class GoogleExampleLibraryagentV1ListBooksResponse(BaseModel):
    books: Optional[List[GoogleExampleLibraryagentV1Book]] = Field(
        None, description='The list of books.'
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='A token to retrieve next page of results. Pass this value in the ListBooksRequest.page_token field in the subsequent call to `ListBooks` method to retrieve the next page of results.',
    )


class GoogleExampleLibraryagentV1Shelf(BaseModel):
    name: Optional[str] = Field(
        None,
        description='Output only. The resource name of the shelf. Shelf names have the form `shelves/{shelf_id}`. The name is ignored when creating a shelf.',
    )
    theme: Optional[str] = Field(None, description='The theme of the shelf')


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class GoogleExampleLibraryagentV1ListShelvesResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None,
        description='A token to retrieve next page of results. Pass this value in the ListShelvesRequest.page_token field in the subsequent call to `ListShelves` method to retrieve the next page of results.',
    )
    shelves: Optional[List[GoogleExampleLibraryagentV1Shelf]] = Field(
        None, description='The list of shelves.'
    )
